### ISSUE TITLE
Fix PHP version constraints

### ISSUE THREAD

**Issue by DaveLiddament** [DaveLiddament/php-language-extensions#14]
PHP version constraints are, I think, incorrect: 

From [composer.json](https://github.com/DaveLiddament/php-language-extensions/blob/93f78a967df542f9abef9a976642bff1fba5cfba/composer.json#L25)

Constraints are: 
```
"php": "^8.0 || ^8.1 || ^8.2"
```

I *think* this will allow 8.3, which is wrong as we don't know 8.3 will introduce a break to attributes. (Admittedly it is very unlikely that it will). 

Version should either be:

```
"php": "8.0.* || 8.1.* || 8.2.*"
```

or 

```
"php": ">=8.0 <8.3"
```

**Comment by DaveLiddament** [comment]
@szepeviktor any thoughts on this issue? 

I think I misunderstood your suggestion and am pretty sure what I implemented is is wrong.

**Comment by szepeviktor** [comment]
Oh yes!
https://jubianchi.github.io/semver-check/#/^8.0%20||%20^8.1%20||%20^8.2/8.3.0

It is `"php": "~8.0 || ~8.1 || ~8.2"`
https://jubianchi.github.io/semver-check/#/~8.0%20||%20~8.1%20||%20~8.2/8.3.0

**Comment by DaveLiddament** [comment]
@szepeviktor I'm not if I agree with the semver checker tool...

I've just reread the [composer docs](https://getcomposer.org/doc/articles/versions.md#next-significant-release-operators)

I think it is actually this that we want: `"php": "~8.0.0 || ~8.1.0 || ~8.2.0"`


If I understand it correctly `~8.0` equates to `>=8.0  <9`
And `~8.0.0` equates to `>=8.0.0 <8.1`

**Comment by szepeviktor** [comment]
> If I understand it correctly `~8.0` equates to `>=8.0 <9`
> And `~8.0.0` equates to `>=8.0.0 <8.1`

Yes. I'm very bad at numbers.

**Comment by szepeviktor** [comment]
This website shows a warning.
https://jubianchi.github.io/semver-check/#/~8.0/8.3.0

![kép](https://user-images.githubusercontent.com/952007/209345426-6c4dd5c4-7260-47e7-9a7c-dd2221752aa5.png)

**Comment by szepeviktor** [comment]
This one is for Composer only: https://semver.madewithlove.com/?package=php&constraint=~8.0.0&stability=stable
