### ISSUE TITLE
Update #[Friend] to a more obvious name

### ISSUE THREAD

**Issue by DaveLiddament** [DaveLiddament/php-language-extensions#2]
The `#[Friend]` attribute was named after the C++ feature. However this is not likely to be well known in the PHP community. 

Update `#[Friend]` to a more meaningful name. e.g. `#[CallableFrom]`

See [this twitter discussion](https://twitter.com/pelmered/status/1530317975235993604).

**Comment by szepeviktor** [comment]
OFF: This is a very interesting package!

**Comment by DaveLiddament** [comment]
Currently `#[Friend]` is limited to just method calls. In this case `#[CallableFrom]` makes sense. However in the future the `#[Friend]` attribute might be updated to restrict access to member data, constants, etc. For this reason I'll keep the name `#[Friend]`. 

There have also been previous attempts at a `friend` RFC. See: https://wiki.php.net/rfc/friend-classes
