### ISSUE TITLE
Feature request: Override

### ISSUE THREAD

**Issue by priyadi** [DaveLiddament/php-language-extensions#20]
Like Java's override: a method with `#[Override]` must override a method in the parent class, or implements a method of an interface.

**Comment by DaveLiddament** [comment]
Love the suggestion. This is actually coming to PHP in 8.3 as a native language feature. https://wiki.php.net/rfc/marking_overriden_methods

I'd image the static analysis tools will support this once released. 

In the mean time I will add a simple version (that does not take into account traits)

**Comment by DaveLiddament** [comment]
Added in #22
